### ISSUE TITLE
MMT454 : is the memory mecanism still working ?

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#537]
Hi all,
I have an existing memory 1:
```
curl "http://localhost:10001/memories"
{"status":200,"data":[{"id":1,"name":"USERS.fr-en"}]}
```
I'm feeding a sentence pair to memory 1, getting what seems to be a valid result:
{"status":200,"data":{"id":"80000001-0000-0000-0000-00000000002a","memory":1,"size":1,"begin":42,"end":42,"dataChannel":1,"progress":0.0}}

When translating the sentence sent to the memory, whatever the context sent in the URL (for example a word of the source sentence), I always get an empty `contextVector":{"entries":[]}` without any suggestion in the LOG trace:
```
   suggestions = [
   ]
```

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d ,

I have just tested this use cases and I confirm that it is working as expected. This is what I did with a simple "English to Italian" engine:

```bash
$ ./mmt memory list
Total: 0 memories

$ ./mmt memory create test
1: test

$ ./mmt memory add 1 "This is an example" "Questo è un test per Etienne"
Contribution added to memory 1

$ ./mmt translate --context-vector 1:1 "This is an example"
Questo è un test per Etienne
```

and this is the log file:
```
2020-05-19 13:32:13,350 DEBUG eu.modernmt.decoder.neural.NeuralDecoder [pool-2-thread-1] Translation received from neural decoder:
   sentence = This is an example
   translation = Questo è un test per Etienne
   alignment = 0-0 0-5 1-5 2-1 2-5 3-2 3-3 3-4
   suggestions = [
      ScoreEntry{memory=1, language=en → it, sentence=[This, is, an, example], translation=[Questo, è, un, test, per, Etienne], score=1.0}
   ]
```

Can you please share the steps to reproduce your problem?
Thank you!

**Comment by EtienneAb3d** [comment]
My problem occurred using the URL API.
Doing the same with the `mmt` command line, as you did, worked.
Now, the URL API translation is properly using the memory.
It's thus certainly a problem with the ADD URL API command.
I need to investigate on that.
Is there a way to list the content of the memory?

**Comment by EtienneAb3d** [comment]
Possibly an explanation...
In your documentation, the `http://localhost:8045/memories/2/corpus` URL is using a POST. 
https://github.com/modernmt/modernmt/wiki/API-Add-to-Memory
Historically, I used to send the values on the URL itself, thus as GET values. It worked.
I have to find out how to change my code to send them as POST values.

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

the CLI interface uses the API of ModernMT. By the way: we have never changed that API, you can easily check that by navigating the history of that file. The only acceptable method in order to add an entry to the corpus is POST.

Can you please send me the cURLs you're using in order to understand better where the problem. is?

Thank you.

**Comment by EtienneAb3d** [comment]
I think I finally found the bug: the context as string is no more working!
When I send a `context-vector` param in both the URL API or the command line, it works.
When I send a `context` param in the URL API, it doesn't work. It behaves exactly as if there was no context defined.
When I send a `--context` option on the command line, I get this error message:
```
./mmt translate --context "Firefox" -e FREN
ERROR Unexpected exception: list indices must be integers or slices, not str
```

**Comment by davidecaroselli** [comment]
Hi @EtienneAb3d 

thanks for the clarification. I have just pushed a fix in `master` for a bug in the python cli script that was causing the error `ERROR Unexpected exception: list indices must be integers or slices, not str`. Luckily, this was just a CLI problem, while the API works as expected.

So no, with the latest `master` fix, this is my test starting from a blank engine:
```
$ ./mmt memory import -p examples/data/train/europarl.en examples/data/train/europarl.it 
Importing europarl... [========================================] 100.0% 00:03 
IMPORT SUCCESS

$ ./mmt translate --context "Mr President"

ModernMT Translate command line
>> Context: europarl 20.7%

This is a test
> Questo è un test
```

As you can see, the Context is successfully computed now with a "20.7%" match. 

Finally, let me also add one thing that can probably be misleading in your experiments: single contributions are always immediately added to both Context Analyzer and Memory. However, for performance reasons, the Context analyzer indexing is triggered only after a minimum amount of content has been added. So, adding a single sentence in an empty memory is not enough to trigger the Context Analyzer indexing. 

This behavior is the same from the very first implementation of the Context Analyzer and it has not changed during time.

**Comment by EtienneAb3d** [comment]
In experiments reported in past posts here, I used some new memories adding only one sentence pair in it, and then use it to translate right after this. Most of the time, the single pair memory was properly used. In very few cases it wasn't.
In my current case, the memory is never used, even few days after the sentence pair is added.

**Comment by EtienneAb3d** [comment]
I did an `git pull` and was surprised by the number of impacted files on this 4.5.4 release.
I did a `python3 setup.py` making `cassandra` and `kafka` to be downloaded again.
Then `mvn clean install`
.... Still the same problem

Here is precisely what seems to work or not:

1) adding `context_vector` on the URL 
- I properly have an entry in the `suggestions` set with a scoring in the LOG trace 
- I do not have any `contextVector":{"entries":[...]}` in the LOG trace. Possibly this is normal since the context vector was enforced by the parameter?
- the LOG trace is showing a URL including the `context_vector` parameter, identical to the one I sent, even if I'm playing with the parameter order.
2) adding `--context-vector` on the `mmt` command line
Identical to point 1. This time the LOG trace is showing a rebuilt URL including the `context_vector` parameter.
3) adding `context` on the URL with a word of the sentence (to translate, and already stored)
- I get an empty suggestions set in the LOG trace
- I get an empty `contextVector":{"entries":[]}` in the LOG trace
- the LOG trace is showing a URL including the `context` parameter, identical to the one I sent, even if I'm playing with the parameter order.
4) adding `--context` on the command line
- it no more returns with an error
- I get an empty suggestions set in the LOG trace
- I do not have any `contextVector":{"entries":[...]}` in the LOG trace
- the LOG trace is showing a rebuilt URL without the `context` parameter.

**Comment by EtienneAb3d** [comment]
I tried with older MMT44, MMT421, MMT412.
Starting with a fresh new model just after training.
Manually creating a memory and feeding it with the `mmt` command line.
Can't get it working.
The only working configuration is when using the `context-vector` parameter.
I think I will temporarily change my code to use this `context-vector` parameter, waiting for the `context` parameter to work again. It's a possible workaround.

**Comment by EtienneAb3d** [comment]
An idea: in your test above, you are using the default model, while in my case I'm using several named model. If the `context` parameter is only evaluating the default model's memories, it could explain it is working in your case and not in mine.

**Comment by mzeidhassan** [comment]
Hi @davidecaroselli  and @EtienneAb3d 

I am having the same issue. I confirm that passing context_vector works. 

@davidecaroselli are you going to revert back to context or not? Should we change the code to make it now work with context_vector instead?

Look forward to hearing from you.

Thanks

**Comment by davidecaroselli** [comment]
As I have explained in the previous posts, **nothing changed from previous versions**. I have fixed a CLI problem that Etienne spot, but speaking of APIs all ModernMT versions share the same behavior. You can easily check it yourself by downloading previous versions (with Docker it should be much easier)

**Comment by EtienneAb3d** [comment]
@davidecaroselli, as I said above, for me, there is really still a problem. And this problem might be an old one.

**Comment by mzeidhassan** [comment]
@EtienneAb3d I had the same issue as yours when it comes to context because I didn't have a memory. Once I imported a memory, I got something like this:
![image](https://user-images.githubusercontent.com/7589948/84940071-8c182200-b09c-11ea-8fac-c3d3dc89da5f.png)

It's worth-mentioning that I am using engine 'default'.

**Comment by mzeidhassan** [comment]
I would like also to add that sometimes and for unknown reasons, the memory functionality doesn't work properly, i.e., I create a memory, but nothing is saved to it for some reason. Once I stop the engine, restart it again, it works fine, and entries are added to the memory. I am not sure if you have experienced this before, but this happened a couple of times at my end.

**Comment by EtienneAb3d** [comment]
All is explain above about my own case, mainly here:
https://github.com/modernmt/modernmt/issues/537#issuecomment-631251346
https://github.com/modernmt/modernmt/issues/537#issuecomment-631318270

To be sure your memory is used, you have to start `mmt` with option `-v 3`, translate something, then have a look at the LOG file: you should get the stored sentence pair used to tune.
